export enum PermissionTypes {
  USER_ACTIVITIES ="USER_ACTIVITIES", ADD_TRAVEL_CONNECTION = "ADD_TRAVEL_CONNECTION",
  CREATE_USER_WITH_ROLE = "CREATE_USER_WITH_ROLE", SCAN_QR_CODE = "SCAN_QR_CODE"
}
